config/routes.rb
Rails.application.routes.draw do

  root                                  'pages#root'

  get     'main'                         =>  'pages#main'

  get    'start'                         =>  'games#start'
  get    'gameover'                         =>  'games#gameover'
  get    'game'                         =>  'games#game'
  get    'skip'                         =>  'games#skip'
  post   'word_check'     =>  'games#word_check'

  # receiving emails
  post  'post'    =>  'emails#post'
  get   'success' =>  'emails#success'

  get 'set_cookie' =>  'cookie#set_cookie'
  get 'get_cookie' =>  'cookie#getter'
  get 'cookie/index'
  get 'cookie/setter'


  root                          'pages#game'



  get                           'newsletters/create'
  post                          'newsletters/create'
  get     'newsletter'      =>  'newsletters#new'
  get     'signup'          =>  'users#new'
  get     'login'           =>  'sessions#new'
  post    'login'           =>  'sessions#create'
  delete  'logout'          =>  'sessions#destroy'
  get     'resend'          =>  'password_resends#new'
  post    'resend'          =>  'password_resends#create'
  get     'about'           =>  'pages#about'
  get     'help'            =>  'pages#help'
  get     'contact'         =>  'pages#contact'
  get     'landing_page'         =>  'pages#landing_page'

  get     'privacy'         =>  'pages#privacy'
  get     'terms'           =>  'pages#terms'
  get     'invite'          =>  'invites#new'
  get     'auth/:provider/callback', to: 'sessions#social_create'
  # get     'auth/facebook', to: 'sessions#social_create'

  # resources :merchants, only: [:edit, :update]
  resources :resumes
  resources :projects
  resource :newsletters
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :password_resends,    only: [:new, :create]
  resource :invites
end

app/controllers/password_resends_controller.rb
class PasswordResendsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:activation_resend][:email].downcase)
    if user
      if user.activated?
        flash[:warning] = "User with this email address has already been
                          activated. Please login"
        redirect_to login_path
      else
        user.resend_activation_link
        flash[:warning] = "Activation link resent. Please check your email"
        redirect_to root_url
      end
    elsif
      flash.now[:danger] = 'User with this email address does not exist!'
      render 'new'
    end
  end
end

app/helpers/password_resends_helper.rb
module PasswordResendsHelper
end

app/views/password_resends/new.html.erb
<% provide(:title, 'Resend') %>

<%= link_to "Login", login_path, class: "login-button" %>

<div class="section">
  <div class="page-title">
    <h1>Resend Activation email</h1>
  </div>

<div class="form-container">
 <div class="col-md-6 col-md-offset-3">
   <%= form_for(:activation_resend, url: resend_path) do |f| %>
   <div class="field">
     <%= f.email_field :email, placeholder: "email", class: 'form-control' %>
   </div>
     <%= f.submit "Send activation link", class: "short-submit-button" %>
   <% end %>

   <div class="notice">
     <p>
       New User? <%= link_to "Sign up now!", signup_path, class: 'small-links' %>
     </p>
   </div>
  </div>
</div>