config/routes.rb
Rails.application.routes.draw do

  root                                  'pages#root'

  get     'main'                         =>  'pages#main'

  get    'start'                         =>  'games#start'
  get    'gameover'                         =>  'games#gameover'
  get    'game'                         =>  'games#game'
  get    'skip'                         =>  'games#skip'
  post   'word_check'     =>  'games#word_check'

  # receiving emails
  post  'post'    =>  'emails#post'
  get   'success' =>  'emails#success'

  get 'set_cookie' =>  'cookie#set_cookie'
  get 'get_cookie' =>  'cookie#getter'
  get 'cookie/index'
  get 'cookie/setter'


  root                          'pages#game'



  get                           'newsletters/create'
  post                          'newsletters/create'
  get     'newsletter'      =>  'newsletters#new'
  get     'signup'          =>  'users#new'
  get     'login'           =>  'sessions#new'
  post    'login'           =>  'sessions#create'
  delete  'logout'          =>  'sessions#destroy'
  get     'resend'          =>  'password_resends#new'
  post    'resend'          =>  'password_resends#create'
  get     'about'           =>  'pages#about'
  get     'help'            =>  'pages#help'
  get     'contact'         =>  'pages#contact'
  get     'landing_page'         =>  'pages#landing_page'

  get     'privacy'         =>  'pages#privacy'
  get     'terms'           =>  'pages#terms'
  get     'invite'          =>  'invites#new'
  get     'auth/:provider/callback', to: 'sessions#social_create'
  # get     'auth/facebook', to: 'sessions#social_create'

  # resources :merchants, only: [:edit, :update]
  resources :resumes
  resources :projects
  resource :newsletters
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :password_resends,    only: [:new, :create]
  resource :invites
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessor :name, :email etc etc is no longer needed because rails nows
    # these attributes exists as columns in the database
    # rails talks to the active record to get them


  # has_many :projects, dependent: :destroy
  has_many :games
  require 'securerandom'

  attr_accessor :remember_token, :activation_token, :reset_token
  # before_save   :downcase_email
  before_create :create_activation_digest
  after_create  :actions_after_successful_signup
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: { minimum: 8 }, allow_blank: true

  #Returns the hash Digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  #Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # this was written to facture account_activation_controller line:10
  def activate
    self.update_attribute(:activated, true)
    self.update_attribute(:activated_at, Time.zone.now)
  end

  # sends activation email
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

# Sets the password reset attributes
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def resend_activation_link
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
    update_attribute(:activation_digest, User.digest(activation_token))
    self.send_activation_email
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.password = SecureRandom.urlsafe_base64
      user.activated = true
      params = { "name" => user.name, "email" => user.email}
      begin
        user.save!
      rescue => error
        user.update(params)
      end
    end
  end

  def actions_after_successful_signup
    if self.newsletter == true
      newsletter = Mailchimp::API.new("mailchimp-api-key-here")
      newsletter.lists.subscribe("mailchimp-list-id-here",
                       { "email" => self.email})
    end
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    # @microposts = @user.microposts.paginate(page: params[:page])
  end

  def index
    # this is here because app crashes when signup form is submitted empty-
    # and refresh button is pressed
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    # checking if email has been updated
    old_email = current_user.email
    new_email = params["user"]["email"]
    # checking if newsletter has been updated
    old_newsletter = current_user.newsletter
    if params["user"]["newsletter"] == "1"
      new_newsletter = true
    else
      new_newsletter = false
    end

    if old_email != new_email
      # new email address
      if old_newsletter == true
        if new_newsletter == false
          # debugger
          # unsubscriber from mailchimp
          newsletter_unsubscribe(old_email)
        else
          # debugger
          # a subscriber => update mailchimp
          newsletter_update(old_email, new_email)
        end
      elsif new_newsletter == true
        # new mailchimp subscription
        newsletter_subscribe(new_email)
      end
    elsif old_newsletter != new_newsletter
      # no change in email address change only in subscription
      if new_newsletter == true
        # debugger
        # new mailchimp subscription
        newsletter_subscribe(old_email)
      else
        # debugger
        # mailchimp unsubscribe
        newsletter_unsubscribe(old_email)
      end
    end


    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user unless performed?
    elsif
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def newsletter_subscribe(email)
    begin
      # raise "error"
      response = Mailchimp::API.new("mailchimp-api-key-here")
      result = response.lists.subscribe("mailchimp-list-id-here", { "email" => email})
    rescue
      # f383712141 when ever this code is change below address should be changed too!
      newsletter_unsubscribe(email)
      redirect_to "address to where to redirect to incase of failure"
    end
  end

  def newsletter_unsubscribe(email)
    begin
      response = Mailchimp::API.new("mailchimp-api-key-here")
      response.lists.unsubscribe("mailchimp-list-id-here", { "email" => email})
    rescue
      # incase user has "." in the email address and subscribed with out the "."
      # as gmail ignores the "." between firstname and lastname
      # this was not tested properly!
      flash[:info] = '                                                         It appears that email address on file is different from one you subscribed with, Click unsubscribe from the email we previous sent you'
    end
  end

  def newsletter_update(old_email, new_email)
    begin
      response = Mailchimp::API.new("mailchimp-api-key-here")
      subscriber = response.helper.search_members(current_user.email, id = "mailchimp-list-id-here")
      # debugger
      response.lists.update_member("mailchimp-list-id-here",{'email' => old_email},{'email' => new_email})
    rescue
      newsletter_unsubscribe(old_email)
      redirect_to "address to where to redirect to incase of failure"
    end
  end

  private
    # this technique is called strong parameters incase i want to google this later
    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :password,
                                   :password_confirmation,
                                   :newsletter)
    end

    #confirms a logged-in user_params
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    #confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
 end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

# module UsersHelper
#
#   # Returns the graavataar for the given user.
#   def gravatar_for(user)
#     gravatar_id = Digest::MD5::hexdigest(@user.email.downcase)
#     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
#     image_tag(gravatar_url, alt:user.name, class: "gravatar")
#   end
# end

app/views/users/edit.html.erb
<!-- passed from controller: @user = User.new -->

<!-- <div class="gravatar-edit">
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div> -->

<% provide(:title, 'Edit user') %>
<div class="page-title">
  <h2>Your profile</h2>
</div>

<div class="form-container">
 <div class="col-md-6 col-md-offset-3">
   <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages' %>

     <div class="field">
       <!-- <%= f.label :name %> -->
       <%= f.text_field :name, class: 'form-control' %><br>

       <!-- <%= f.label :email %> -->
       <%= f.email_field :email, class: 'form-control' %><br>

       <!-- <%= f.label :password %> -->
       <%= f.password_field :password, placeholder: "new password", class: 'form-control' %><br>

       <!-- <%= f.label :password_confirmation, "Confirmation" %> -->
       <%= f.password_field :password_confirmation, placeholder: "password confirmation", class: 'form-control' %>

       <div class="checkbox-container">
         <div class="field">
           <%= f.label :newsletter, "Newsletter signup", class: 'checkbox-label' %>
           <%= f.check_box :newsletter, class: 'checkbox' %>
         </div>
       </div>
     </div>

     <%= f.submit "Save changes", class: "short-submit-button" %>
   <% end %>
  </div>
</div>

app/views/users/new.html.erb
<!-- passed from controller: @user = User.new -->

<% provide(:title, 'Sign up') %>

<div class="page-title">
  <h1>Sign up</h1>
</div>

<div class="form-container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="field">
      <!-- <%= f.label :name %> -->
      <%= f.text_field :name, class: 'form-control', placeholder: 'what is your name?' %><br>

      <!-- <%= f.label :email %> -->
      <%= f.email_field :email, class: 'form-control', placeholder: 'what is your email' %><br>

      <!-- <%= f.label :password %> -->
      <%= f.password_field :password, class: 'form-control', placeholder: 'password' %><br>

      <!-- <%= f.label :password_confirmation, "Confirmation" %> -->
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'password confirmation' %>
    </div>
    <div class="notice">
      <p>
        Already have an account? <%= link_to "Login here", login_path, class: 'small-links' %>
      </p>
    </div>

    <div class="checkbox-container">
      <div class="field">
        <%= f.label :newsletter, "Newsletter signup", class: 'checkbox-label' %>
        <%= f.check_box :newsletter, class: 'checkbox' %>
      </div>
    </div>
    <!-- <div class="field">
      <%= f.label :newsletter, "Newsletter", class: 'checkbox-label' %>
      <%= f.check_box :newsletter, class: 'checkbox' %>
    </div> -->
      <%= f.submit "Create my account", class: "short-submit-button" %>
        <div class="notice">
          <p>
            By clicking 'Sign Up' you are agreeing that you have read and agreed to
            our <%= link_to 'Terms of Service', terms_path, class: 'small-links' %> and
            <%= link_to 'Privacy Policy', privacy_path, class: 'small-links' %>
          </p>

          <p>
            Activation link lost in the mail?
            <%= link_to "Click here", resend_path, class: 'small-links' %>
          </p>
        </div>
      <!-- this was placed in double contailer due to leaking -->
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="section">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>