config/routes.rb
Rails.application.routes.draw do

  root                                  'pages#root'

  get     'main'                         =>  'pages#main'

  get    'start'                         =>  'games#start'
  get    'gameover'                         =>  'games#gameover'
  get    'game'                         =>  'games#game'
  get    'skip'                         =>  'games#skip'
  post   'word_check'     =>  'games#word_check'

  # receiving emails
  post  'post'    =>  'emails#post'
  get   'success' =>  'emails#success'

  get 'set_cookie' =>  'cookie#set_cookie'
  get 'get_cookie' =>  'cookie#getter'
  get 'cookie/index'
  get 'cookie/setter'


  root                          'pages#game'



  get                           'newsletters/create'
  post                          'newsletters/create'
  get     'newsletter'      =>  'newsletters#new'
  get     'signup'          =>  'users#new'
  get     'login'           =>  'sessions#new'
  post    'login'           =>  'sessions#create'
  delete  'logout'          =>  'sessions#destroy'
  get     'resend'          =>  'password_resends#new'
  post    'resend'          =>  'password_resends#create'
  get     'about'           =>  'pages#about'
  get     'help'            =>  'pages#help'
  get     'contact'         =>  'pages#contact'
  get     'landing_page'         =>  'pages#landing_page'

  get     'privacy'         =>  'pages#privacy'
  get     'terms'           =>  'pages#terms'
  get     'invite'          =>  'invites#new'
  get     'auth/:provider/callback', to: 'sessions#social_create'
  # get     'auth/facebook', to: 'sessions#social_create'

  # resources :merchants, only: [:edit, :update]
  resources :resumes
  resources :projects
  resource :newsletters
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :password_resends,    only: [:new, :create]
  resource :invites
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def start
    board = generate_game
    new_game = Game.create(user_id: current_user.id, state: board)
    redirect_to game_path(game_id: new_game)
  end

  def skip
    game_id = params[:game_id].to_i
    game = Game.find(game_id)
    # loop through the affected lanes
    board = eval(game.state)
    score = game.score

    # Move letters to left and add letters
    board.each do |lane|
      if lane[1][1].join != ""
        if lane[1][0][1].to_i < 1
          redirect_to gameover_path(score: score) and return
        else
          lane[1][0] = "#0"
        end
      end

      # remove first letter
      lane[1].delete_at(1)

      # add letter to last
      array = ["E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "A",
        "A", "A", "A", "A", "A", "A", "A", "A", "I", "I", "I", "I", "I", "I",
        "I", "I", "I", "O", "O", "O", "O", "O", "O", "O", "O", "N", "N", "N",
        "N", "N", "N", "R", "R", "R", "R", "R", "R", "T", "T", "T", "T", "T",
        "T", "L", "L", "L", "L", "S", "S", "S", "S", "U", "U", "U", "U", "D",
        "D", "D", "D", "G", "G", "G", "B", "B", "C", "C", "M", "M", "P", "P",
        "F", "F", "H", "H", "V", "V", "W", "W", "Y", "Y", "K", "J", "X", "Q", "Z"]
      size = rand(1...4)
      lane[1] << array.sample(size)
    end

    game.update(state: board)
    redirect_to game_path(game_id: game_id)
  end

  def gameover
    @games = current_user.games
    @score = params[:score]
  end

  def game
    @game_id = params[:game_id]
    game = Game.find(@game_id)
    @board = eval(game.state)

    @word = ""
    @score = game.score
  end

  def generate_game
    board = {
      #  lane1: ["#1","","F","C","A","E","G","U","N","E"],
      #  lane2: ["#2","Q","E","A","","D","M"],
      #  lane3: ["#3","","J","P","D","H","K","V"],
      #  lane4: ["#4","I","","","","","G","Q","","S","I"],
      #  lane5: ["#5","","","","","I","",""],
      #  lane6: ["#6","O","","V","O","","A","D","Z"]

      lane1: ["#1",[""],[""],[""],[""]],
      lane2: ["#1",[""],[""],[""],[""]],
      lane3: ["#1",[""],[""],[""],[""]],
      # lane4: ["#1",[""],[""],[""],[""]],
      # lane5: ["#1",[""],[""],[""],[""]],
      # lane6: ["#1",[""],[""],[""],[""]]
    }
    array = ["E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "A",
      "A", "A", "A", "A", "A", "A", "A", "A", "I", "I", "I", "I", "I", "I",
      "I", "I", "I", "O", "O", "O", "O", "O", "O", "O", "O", "N", "N", "N",
      "N", "N", "N", "R", "R", "R", "R", "R", "R", "T", "T", "T", "T", "T",
      "T", "L", "L", "L", "L", "S", "S", "S", "S", "U", "U", "U", "U", "D",
      "D", "D", "D", "G", "G", "G", "B", "B", "C", "C", "M", "M", "P", "P",
      "F", "F", "H", "H", "V", "V", "W", "W", "Y", "Y", "K", "J", "X", "Q", "Z"]
    board.each do |lane|
      # add letter to last
      size = rand(1...4)
      lane[1] << array.sample(size)
    end

    return board
  end

  def word_check
    game_id = params[:game_id].to_i
    game = Game.find(game_id)
    word = params[:answer].downcase
    match = File.read('words.txt').match(/\b#{word}\b/)
    if match.nil?
      flash[:warning] = "#{word} is not a word"
      redirect_to game_path(game_id: game_id)
    else
      # loop through the affected lanes
      board = eval(game.state)
      reference = params[:reference].split(",")

      reference.reverse.each do |ref|
        # remove letters
          board["lane#{ref[0]}".to_sym][ref[1].to_i][ref[2].to_i] = ""
      end

      # Move letters to left and add letters
      board.each do |lane|
        if lane[1][1].join != ""
          if lane[1][0][1].to_i < 1
            old_score = game.score
            score = calculate_score(word.upcase) + old_score

            game.update(score: score)
            redirect_to gameover_path(score: score) and return
          else
            lane[1][0] = "#0"
          end
        end

        # remove first letter
        lane[1].delete_at(1)

        # add letter to last
        array = ["E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "A",
          "A", "A", "A", "A", "A", "A", "A", "A", "I", "I", "I", "I", "I", "I",
          "I", "I", "I", "O", "O", "O", "O", "O", "O", "O", "O", "N", "N", "N",
          "N", "N", "N", "R", "R", "R", "R", "R", "R", "T", "T", "T", "T", "T",
          "T", "L", "L", "L", "L", "S", "S", "S", "S", "U", "U", "U", "U", "D",
          "D", "D", "D", "G", "G", "G", "B", "B", "C", "C", "M", "M", "P", "P",
          "F", "F", "H", "H", "V", "V", "W", "W", "Y", "Y", "K", "J", "X", "Q", "Z"]
        size = rand(1...4)
        lane[1] << array.sample(size)
      end

      # score
      # score = word.split("").count
      old_score = game.score
      score = calculate_score(word.upcase) + old_score

      game.update(state: board, score: score)
      redirect_to game_path(game_id: game_id)
    end
  end

  def calculate_score(word)
    score = 0
    word.split("").each  do |letter|
      if "EAIONRTLSU".include?(letter)
        score += 1
      elsif "DG".include?(letter)
        score += 2
      elsif "BCMP".include?(letter)
        score += 3
      elsif "FHVWY".include?(letter)
        score += 4
      elsif "K"
        score += 5
      elsif "JX".include?(letter)
        score += 8
      else "QZ".include?(letter)
        score += 10
      end
    end

    return score
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/game.html.erb
<% provide(:title, "W vs C") %>

<div class="game">
    <p><%= "Score: #{@score}" %></p>
  <center><table>
    <!-- <tr>
      <th>Castles</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
    </tr> -->

    <!-- lane1 -->
    <tr>
      <% if @board[:lane1][0][1].to_i > 0 %>
          <td class="castle" data-castle=<%= "#{@board[:lane1][0]}" %>><%= "🏰" %></td>
        <% else %>
          <td class="castle" data-castle=<%= "#{@board[:lane1][0]}" %>><%= "" %></td>
      <% end %>
      <td>
       <span data-ref="110" id="110"><%= "#{@board[:lane1][1][0]}" %></span>
       <span data-ref="111" id="111"><%= "#{@board[:lane1][1][1]}" %></span>
       <span data-ref="112" id="112"><%= "#{@board[:lane1][1][2]}" %></span>
      </td>
      <td>
        <span data-ref="120" id="120"><%= "#{@board[:lane1][2][0]}" %></span>
        <span data-ref="121" id="121"><%= "#{@board[:lane1][2][1]}" %></span>
        <span data-ref="122" id="122"><%= "#{@board[:lane1][2][2]}" %></span>
      </td>
      <td>
        <span data-ref="130" id="130"><%= "#{@board[:lane1][3][0]}" %></span>
        <span data-ref="131" id="131"><%= "#{@board[:lane1][3][1]}" %></span>
        <span data-ref="132" id="132"><%= "#{@board[:lane1][3][2]}" %></span>
      </td>
      <td>
        <span data-ref="140" id="140"><%= "#{@board[:lane1][4][0]}" %></span>
        <span data-ref="141" id="141"><%= "#{@board[:lane1][4][1]}" %></span>
        <span data-ref="142" id="142"><%= "#{@board[:lane1][4][2]}" %></span>
      </td>
      <td>
        <span data-ref="150" id="150"><%= "#{@board[:lane1][5][0]}" %></span>
        <span data-ref="151" id="151"><%= "#{@board[:lane1][5][1]}" %></span>
        <span data-ref="152" id="152"><%= "#{@board[:lane1][5][2]}" %></span>
      </td>
    </tr>

    <!-- lane2 -->
    <tr>
      <% if @board[:lane2][0][1].to_i > 0 %>
          <td class="castle" data-castle=<%= "#{@board[:lane2][0]}" %>><%= "🏰" %></td>
        <% else %>
          <td class="castle" data-castle=<%= "#{@board[:lane2][0]}" %>><%= "" %></td>
      <% end %>
      <td>
       <span data-ref="210" id="210"><%= "#{@board[:lane2][1][0]}" %></span>
       <span data-ref="211" id="211"><%= "#{@board[:lane2][1][1]}" %></span>
       <span data-ref="212" id="212"><%= "#{@board[:lane2][1][2]}" %></span>
      </td>
      <td>
        <span data-ref="220" id="220"><%= "#{@board[:lane2][2][0]}" %></span>
        <span data-ref="221" id="221"><%= "#{@board[:lane2][2][1]}" %></span>
        <span data-ref="222" id="222"><%= "#{@board[:lane2][2][2]}" %></span>
      </td>
      <td>
        <span data-ref="230" id="230"><%= "#{@board[:lane2][3][0]}" %></span>
        <span data-ref="231" id="231"><%= "#{@board[:lane2][3][1]}" %></span>
        <span data-ref="232" id="232"><%= "#{@board[:lane2][3][2]}" %></span>
      </td>
      <td>
        <span data-ref="240" id="240"><%= "#{@board[:lane2][4][0]}" %></span>
        <span data-ref="241" id="241"><%= "#{@board[:lane2][4][1]}" %></span>
        <span data-ref="242" id="242"><%= "#{@board[:lane2][4][2]}" %></span>
      </td>
      <td>
        <span data-ref="250" id="250"><%= "#{@board[:lane2][5][0]}" %></span>
        <span data-ref="251" id="251"><%= "#{@board[:lane2][5][1]}" %></span>
        <span data-ref="252" id="252"><%= "#{@board[:lane2][5][2]}" %></span>
      </td>
    </tr>

    <!-- lane3 -->
    <tr>
      <% if @board[:lane3][0][1].to_i > 0 %>
          <td class="castle" data-castle=<%= "#{@board[:lane3][0]}" %>><%= "🏰" %></td>
        <% else %>
          <td class="castle" data-castle=<%= "#{@board[:lane3][0]}" %>><%= "" %></td>
      <% end %>
      <td>
       <span data-ref="310" id="310"><%= "#{@board[:lane3][1][0]}" %></span>
       <span data-ref="311" id="311"><%= "#{@board[:lane3][1][1]}" %></span>
       <span data-ref="312" id="312"><%= "#{@board[:lane3][1][2]}" %></span>
      </td>
      <td>
        <span data-ref="320" id="320"><%= "#{@board[:lane3][2][0]}" %></span>
        <span data-ref="321" id="321"><%= "#{@board[:lane3][2][1]}" %></span>
        <span data-ref="322" id="322"><%= "#{@board[:lane3][2][2]}" %></span>
      </td>
      <td>
        <span data-ref="330" id="330"><%= "#{@board[:lane3][3][0]}" %></span>
        <span data-ref="331" id="331"><%= "#{@board[:lane3][3][1]}" %></span>
        <span data-ref="332" id="332"><%= "#{@board[:lane3][3][2]}" %></span>
      </td>
      <td>
        <span data-ref="340" id="340"><%= "#{@board[:lane3][4][0]}" %></span>
        <span data-ref="341" id="341"><%= "#{@board[:lane3][4][1]}" %></span>
        <span data-ref="342" id="342"><%= "#{@board[:lane3][4][2]}" %></span>
      </td>
      <td>
        <span data-ref="350" id="350"><%= "#{@board[:lane3][5][0]}" %></span>
        <span data-ref="351" id="351"><%= "#{@board[:lane3][5][1]}" %></span>
        <span data-ref="352" id="352"><%= "#{@board[:lane3][5][2]}" %></span>
      </td>
    </tr>

    <!-- lane4 -->
    <% if @board[:lane4] != nil %>
      <tr>
        <% if @board[:lane4][0][1].to_i > 0 %>
            <td class="castle" data-castle=<%= "#{@board[:lane4][0]}" %>><%= "🏰" %></td>
          <% else %>
            <td class="castle" data-castle=<%= "#{@board[:lane4][0]}" %>><%= "" %></td>
        <% end %>
        <td>
         <span data-ref="410" id="410"><%= "#{@board[:lane4][1][0]}" %></span>
         <span data-ref="411" id="411"><%= "#{@board[:lane4][1][1]}" %></span>
         <span data-ref="412" id="412"><%= "#{@board[:lane4][1][2]}" %></span>
        </td>
        <td>
          <span data-ref="420" id="420"><%= "#{@board[:lane4][2][0]}" %></span>
          <span data-ref="421" id="421"><%= "#{@board[:lane4][2][1]}" %></span>
          <span data-ref="422" id="422"><%= "#{@board[:lane4][2][2]}" %></span>
        </td>
        <td>
          <span data-ref="430" id="430"><%= "#{@board[:lane4][3][0]}" %></span>
          <span data-ref="431" id="431"><%= "#{@board[:lane4][3][1]}" %></span>
          <span data-ref="432" id="432"><%= "#{@board[:lane4][3][2]}" %></span>
        </td>
        <td>
          <span data-ref="440" id="440"><%= "#{@board[:lane4][4][0]}" %></span>
          <span data-ref="441" id="441"><%= "#{@board[:lane4][4][1]}" %></span>
          <span data-ref="442" id="442"><%= "#{@board[:lane4][4][2]}" %></span>
        </td>
        <td>
          <span data-ref="450" id="450"><%= "#{@board[:lane4][5][0]}" %></span>
          <span data-ref="451" id="451"><%= "#{@board[:lane4][5][1]}" %></span>
          <span data-ref="452" id="452"><%= "#{@board[:lane4][5][2]}" %></span>
        </td>
      </tr>
    <% end %>

    <!-- lane5 -->
    <% if @board[:lane5] != nil %>
      <tr>
        <% if @board[:lane5][0][1].to_i > 0 %>
            <td class="castle" data-castle=<%= "#{@board[:lane5][0]}" %>><%= "🏰" %></td>
          <% else %>
            <td class="castle" data-castle=<%= "#{@board[:lane5][0]}" %>><%= "" %></td>
        <% end %>
        <td>
         <span data-ref="510" id="510"><%= "#{@board[:lane5][1][0]}" %></span>
         <span data-ref="511" id="511"><%= "#{@board[:lane5][1][1]}" %></span>
         <span data-ref="512" id="512"><%= "#{@board[:lane5][1][2]}" %></span>
        </td>
        <td>
          <span data-ref="520" id="520"><%= "#{@board[:lane5][2][0]}" %></span>
          <span data-ref="521" id="521"><%= "#{@board[:lane5][2][1]}" %></span>
          <span data-ref="522" id="522"><%= "#{@board[:lane5][2][2]}" %></span>
        </td>
        <td>
          <span data-ref="530" id="530"><%= "#{@board[:lane5][3][0]}" %></span>
          <span data-ref="531" id="531"><%= "#{@board[:lane5][3][1]}" %></span>
          <span data-ref="532" id="532"><%= "#{@board[:lane5][3][2]}" %></span>
        </td>
        <td>
          <span data-ref="540" id="540"><%= "#{@board[:lane5][4][0]}" %></span>
          <span data-ref="541" id="541"><%= "#{@board[:lane5][4][1]}" %></span>
          <span data-ref="542" id="542"><%= "#{@board[:lane5][4][2]}" %></span>
        </td>
        <td>
          <span data-ref="550" id="550"><%= "#{@board[:lane5][5][0]}" %></span>
          <span data-ref="551" id="551"><%= "#{@board[:lane5][5][1]}" %></span>
          <span data-ref="552" id="552"><%= "#{@board[:lane5][5][2]}" %></span>
        </td>
      </tr>
    <% end %>

    <% if @board[:lane6] != nil %>
    <!-- lane6 -->
      <tr>
        <% if @board[:lane6][0][1].to_i > 0 %>
            <td class="castle" data-castle=<%= "#{@board[:lane6][0]}" %>><%= "🏰" %></td>
          <% else %>
            <td class="castle" data-castle=<%= "#{@board[:lane6][0]}" %>><%= "" %></td>
        <% end %>
        <td>
         <span data-ref="610" id="610"><%= "#{@board[:lane6][1][0]}" %></span>
         <span data-ref="611" id="611"><%= "#{@board[:lane6][1][1]}" %></span>
         <span data-ref="612" id="612"><%= "#{@board[:lane6][1][2]}" %></span>
        </td>
        <td>
          <span data-ref="620" id="620"><%= "#{@board[:lane6][2][0]}" %></span>
          <span data-ref="621" id="621"><%= "#{@board[:lane6][2][1]}" %></span>
          <span data-ref="622" id="622"><%= "#{@board[:lane6][2][2]}" %></span>
        </td>
        <td>
          <span data-ref="630" id="630"><%= "#{@board[:lane6][3][0]}" %></span>
          <span data-ref="631" id="631"><%= "#{@board[:lane6][3][1]}" %></span>
          <span data-ref="632" id="632"><%= "#{@board[:lane6][3][2]}" %></span>
        </td>
        <td>
          <span data-ref="640" id="640"><%= "#{@board[:lane6][4][0]}" %></span>
          <span data-ref="641" id="641"><%= "#{@board[:lane6][4][1]}" %></span>
          <span data-ref="642" id="642"><%= "#{@board[:lane6][4][2]}" %></span>
        </td>
        <td>
          <span data-ref="650" id="650"><%= "#{@board[:lane6][5][0]}" %></span>
          <span data-ref="651" id="651"><%= "#{@board[:lane6][5][1]}" %></span>
          <span data-ref="652" id="652"><%= "#{@board[:lane6][5][2]}" %></span>
        </td>
      </tr>
    <% end %>
  </table></center>

  <div class="form-container">
    <%= form_for(@word, url: word_check_path) do |f| %>

      <div class="field">
        <%= f.text_field :answer, class: 'game-text-field', value: "" %>
        <%= f.hidden_field :reference, class: 'game-text-field', value: "" %>
        <%= f.hidden_field :game_id, class: 'game-text-field', value: @game_id %>
      </div>

      <%= image_tag('backspace.png', class: "backspace") %>

      <%= f.submit "submit word", class: "submit-word-button" %>
    <% end %>
  </div>
</div>
<%= link_to "Skip", skip_path(game_id: @game_id) %><br>
<%= link_to "Restart", start_path %>

<script>
  var letters = $('span')
  var answer = $("[name='answer']")
  var reference = $("[name='reference']")
  var backspace = $('.backspace')
  var submitButton = $('.submit-word-button')
  letters.on('click', function(event) {
    event.preventDefault();
    // handle letters
    // var myspan =
    var letter = event.target.innerText
    var word = answer[0].value
    var new_ref = event.target.dataset.ref
    var old_ref = reference[0].value
    if (old_ref === "") {
      reference[0].value = `${new_ref}`
      answer[0].value = `${word}${letter}`
      event.currentTarget.style.opacity = 0.3;
    } else {
      if (old_ref.includes(new_ref)) {
      } else {
        answer[0].value = `${word}${letter}`
        reference[0].value = `${old_ref},${new_ref}`
      }
      event.currentTarget.style.opacity = 0.3;
    }


    if (answer[0].value.length > 2) {
      submitButton.show()
    }
  });
  backspace.on('click', function(event) {
    event.preventDefault();
    var word = answer[0].value
    var reference = $("[name='reference']")
    word = word.slice(0, -1);
    answer[0].value = `${word}`

    var old_ref = reference[0].value
    $(`span#${old_ref.slice(-3)}`)[0].style.opacity = 1;
    reference[0].value = old_ref.slice(0, -4);

    if (answer[0].value.length == 2) {
      submitButton.hide()
    }

  });
</script>

app/views/games/gameover.html.erb
<% provide(:title, "Main Menu") %>

<div class="landing-page-intro">
    <h1>GAME OVER</h1>
    <h2><%= "YOUR SCORE IS #{@score}" %></h2>
    <br><br><br><br><br>
    <%= link_to "Start Game", start_path, class: "link" %>

  <% if @games.count == 0 %>
    <h2><%= "You have #{@games.count} Games" %></h2>
  <% else %>
    <h2><%= "You have #{@games.count} Games" %></h2>
  <% end %>
</div>

app/views/games/start.html.erb
<h1>Games#start</h1>
<p>Find me in app/views/games/start.html.erb</p>