config/routes.rb
Rails.application.routes.draw do

  root                                  'pages#root'

  get     'main'                         =>  'pages#main'

  get    'start'                         =>  'games#start'
  get    'gameover'                         =>  'games#gameover'
  get    'game'                         =>  'games#game'
  get    'skip'                         =>  'games#skip'
  post   'word_check'     =>  'games#word_check'

  # receiving emails
  post  'post'    =>  'emails#post'
  get   'success' =>  'emails#success'

  get 'set_cookie' =>  'cookie#set_cookie'
  get 'get_cookie' =>  'cookie#getter'
  get 'cookie/index'
  get 'cookie/setter'


  root                          'pages#game'



  get                           'newsletters/create'
  post                          'newsletters/create'
  get     'newsletter'      =>  'newsletters#new'
  get     'signup'          =>  'users#new'
  get     'login'           =>  'sessions#new'
  post    'login'           =>  'sessions#create'
  delete  'logout'          =>  'sessions#destroy'
  get     'resend'          =>  'password_resends#new'
  post    'resend'          =>  'password_resends#create'
  get     'about'           =>  'pages#about'
  get     'help'            =>  'pages#help'
  get     'contact'         =>  'pages#contact'
  get     'landing_page'         =>  'pages#landing_page'

  get     'privacy'         =>  'pages#privacy'
  get     'terms'           =>  'pages#terms'
  get     'invite'          =>  'invites#new'
  get     'auth/:provider/callback', to: 'sessions#social_create'
  # get     'auth/facebook', to: 'sessions#social_create'

  # resources :merchants, only: [:edit, :update]
  resources :resumes
  resources :projects
  resource :newsletters
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :password_resends,    only: [:new, :create]
  resource :invites
end

app/views/layouts/_absolute_center.html.erb
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>
<p><%= "." %></p>

app/views/layouts/_footer.html.erb
<center>
  <% if current_user %>
    <div class="nav">
      <center><div class="footer-links">
          <%= link_to "Home", root_path, class: "links" %>
          <%= link_to "Projects", projects_path, class: "links" %>
          <%= link_to "Resumes", resumes_path, class: "links" %>
          <%= link_to "Cookies", cookie_index_path, class: "links" %>
      </div></center>
    </div>
  <% else %>
    <div class="landing-footer-links">
      <br><br><br><br><br><br><br><br>
      <!-- <%= link_to "HOME", root_path, class: "links" %> <br><br><br> -->
      <!-- <%= link_to "HOW IT WORKS ", '#', class: "links" %> <br><br><br> -->
      <!-- <%= link_to "ABOUT", about_path, class: "links" %> <br><br><br> -->
      <% unless current_page?(contact_path) %>
        <%= link_to "CONTACT US", contact_path, class: "links" %> <br><br><br>
      <% end %>

      <% unless current_page?(root_path) %>
        <%= link_to "HOME", root_path, class: "links" %> <br><br><br>
      <% end %>

      <!-- <%= link_to "BLOG", '#', class: "links" %> <br><br><br> -->

      <!-- <div class="thin-links"> -->
        <!-- <%= link_to "Privacy", privacy_path, class: "links" %> <br><br><br> -->
        <!-- <%= link_to "Terms", terms_path, class: "links" %> <br><br><br> -->
      <!-- </div> -->

      <!-- <div class="social">
        <%= link_to image_tag("twitter.png", :class => "social-icon"), '#' %>
        <%= link_to image_tag("facebook.png", :class => "social-icon"), '#' %>
        <%= link_to image_tag("google-plus.png", :class => "social-icon"), '#' %>
      </div> -->

      <div class="made-in-toronto">
        <h2>Made in Toronto</h2>
      </div>
    </div>
  <% end %>
</center>

app/views/layouts/_header.html.erb
<header class="header-bar">
    <div class="header-links">
      <div class="the-menu">
        <% if current_user %>
            <!-- <%= image_tag("hamburger.png", alt:"Action",
                          :class => "menubutton")%>
            <div class="outer">
              <div class="dropdown-menu">
                <div class="centered-menu-items">
                  <li> <%= link_to "Home",
                    root_path, class: "menu-item" %></li>
                  <li> <%= link_to "Settings",
                    edit_user_path(current_user), class: "menu-item" %></li>
                  <li> <%= link_to "Invite",
                    invite_path, class: "menu-item" %></li> -->
                  <li> <%= link_to "Logout",
                    logout_path, method: "delete", class: "logout" %></li>
                <!-- </div>
              </div> -->
            </div>
        <% else %>
          <%= link_to "Login", login_path,
            class: "login-button" unless current_page?(login_path) ||
                                  # current_page?(new_password_reset_path) ||
                                  # current_page?(resend_path) ||
                                  # current_page?(privacy_path) ||
                                  # current_page?(terms_path) ||
                                  # current_page?(contact_path) ||
                                  # current_page?(about_path) ||
                                  # current_page?(password_resets) ||
                                  current_page?(root_path)%>
        <% end %>
      </div>
    </div>
</header>

app/views/layouts/_home.html.erb
<% provide(:title, "welcome") %>

<section>
  <div class="home-paragraph-01">
    <h1> Home page</h1>
    <h2> From here you can navigate anywhere in the app while logged in!</h2>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempus urna vel lacinia viverra. Mauris vel aliquet arcu. Aenean hendrerit hendrerit orci, at convallis eros imperdiet in. Vestibulum ultricies ex ac arcu tempor iaculis. Integer sollicitudin, lectus ac tempor consequat, nunc purus fringilla magna, sed fringilla ligula justo eget est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent elementum mi vel dui laoreet lobortis. Sed aliquet ultricies sapien quis egestas. Nulla dignissim faucibus ornare. Aliquam rutrum quam vitae vulputate porttitor. Nam imperdiet urna eu nibh maximus, a maximus ligula fermentum. Etiam blandit metus vitae odio sodales gravida.

      Nulla ornare laoreet magna quis blandit. Proin hendrerit ornare ipsum, vel blandit sem efficitur at. Proin sed malesuada velit, in lobortis ligula. Pellentesque vitae maximus arcu. Fusce tincidunt, magna in lobortis eleifend, massa libero tempor velit, eget faucibus ex dui id sem. Integer vitae mauris ut justo lobortis imperdiet. Curabitur venenatis massa a ex cursus euismod. Duis arcu leo, vulputate eu lectus eget, congue semper libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam augue mi, sollicitudin quis libero nec, interdum auctor leo.

      Integer faucibus orci ut nulla aliquet, vel convallis arcu tincidunt. Quisque volutpat augue arcu. Nulla varius urna ac facilisis posuere. Integer placerat tempus lacus, nec viverra odio sollicitudin eget. Duis sed erat lacus. Cras ut turpis a massa rhoncus tempor vitae eget leo. Sed malesuada ex sit amet pellentesque pretium. Integer rutrum, nisi at faucibus venenatis, magna dolor aliquam ipsum, in lacinia risus dui a urna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque laoreet gravida sem, et egestas mauris viverra in. In auctor mi a vestibulum blandit. Fusce ornare felis at consectetur imperdiet. Cras id est mi. Nam molestie, risus eu pharetra tempor, quam magna lobortis tortor, a tincidunt est risus et diam. Proin tortor lorem, finibus vitae auctor sit amet, finibus ut mi.

      Pellentesque metus sem, sagittis eu dictum eget, cursus sed enim. Mauris ut dolor ac lectus sodales facilisis et at erat. Sed ut accumsan augue. Maecenas lorem neque, consectetur sit amet est sed, sagittis malesuada diam. Aenean hendrerit enim ut metus elementum sollicitudin. Nam feugiat lorem ac tristique tempor. Sed diam enim, efficitur sed aliquet eget, facilisis pulvinar nibh. Vivamus maximus commodo pulvinar. Donec mattis, nulla sed hendrerit auctor, felis massa posuere libero, ac mollis ligula lorem in erat. Donec non diam non arcu tempor molestie sit amet at justo. Sed volutpat ante eu nunc porttitor mollis. Maecenas maximus gravida mi, eget venenatis nisl dapibus vel. Proin diam urna, rutrum ac lorem sit amet, volutpat egestas urna. Vivamus felis eros, vestibulum ac est eu, egestas viverra tortor. Suspendisse potenti.

      Pellentesque nibh libero, tristique non maximus at, efficitur vitae sem. Sed rutrum velit at justo venenatis lobortis. Aenean ut ornare sapien. Fusce et dui rhoncus, finibus ante ut, mattis erat. Nam ut lorem velit. Donec blandit tincidunt ullamcorper. Sed turpis ante, eleifend ut pulvinar quis, molestie sit amet ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam viverra mauris non orci volutpat fringilla. Etiam ligula urna, ultricies nec ligula non, dictum rhoncus ipsum. Nam luctus sit amet nibh at auctor. Cras mattis neque sit amet sem dictum, ac feugiat nunc feugiat. Aliquam a nibh laoreet, varius sem eu, sagittis risus.
    </p>
  </div>
</section>

app/views/layouts/_newsletter.html.erb
  <%= form_for Newsletter.new do |f| %>
    <div class="field">
      <!-- <%= f.label :email %><br /> -->
      <%= f.email_field :email, autofocus: false, placeholder: 'Enter your email', class: "form-control"%>
    </div>

    <div class="actions">
      <%= f.submit "Subscribe", class: 'short-submit-button', id: 'subscribe_button' %>
    </div>
  <% end %>

  <div id="spacing"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= favicon_link_tag "apple-touch-icon.png",
                       rel: "apple-touch-icon",
                       sizes: "100x100",
                       type: "image/png" %>

  <title> <%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    'application',
                              media: 'all' %>

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body data-no-turbolink="true">

  <%= render 'layouts/header' %>

  <% flash.each do |message_type, message| %>
      <center><div class="alert alert-<%= message_type %>"><%= message %></div></center>
  <% end %>

  <center>
      <%= yield %>
  </center>

</body>